name = "buddhi-dwar"
main = "src/index.ts"
compatibility_date = "2025-04-01"

kv_namespaces = [
  { binding = "KV", id = "b0b9c45d98d8407d93b1f3d9a7bf2665" }
]

[vars]
ADMIN_PASSWORD = "2200"

[triggers]
crons = ["0 */6 * * *"]