// APK Builder API Routes for BrainForge Worker
// Handles /apk-builder, /api/apk/build, /api/apk/history

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization',
};

function jsonResponse(data, status = 200) {
  return new Response(JSON.stringify(data), {
    status,
    headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' },
  });
}

function errorResponse(message, status = 500) {
  return jsonResponse({ success: false, error: message }, status);
}

// Inline the HTML so the Worker can serve it without KV bindings
// The HTML is embedded as a base64-decoded string for reliability.
// Replace this placeholder with the actual HTML at build time or import from a module.
const APK_BUILDER_HTML_PLACEHOLDER = '__APK_BUILDER_HTML__';

export async function handleApkRoute(request, env) {
  const url = new URL(request.url);
  const path = url.pathname;

  // CORS preflight
  if (request.method === 'OPTIONS') {
    return new Response(null, { status: 204, headers: CORS_HEADERS });
  }

  // GET /apk-builder — serve the HTML page
  if (path === '/apk-builder' && request.method === 'GET') {
    // Try to fetch from env binding first, fall back to embedded HTML
    let html = APK_BUILDER_HTML_PLACEHOLDER;
    if (env && env.APK_BUILDER_HTML) {
      html = env.APK_BUILDER_HTML;
    }
    return new Response(html, {
      status: 200,
      headers: { ...CORS_HEADERS, 'Content-Type': 'text/html; charset=utf-8' },
    });
  }

  // POST /api/apk/build — trigger a build
  if (path === '/api/apk/build' && request.method === 'POST') {
    return handleApkBuild(request, env);
  }

  // GET /api/apk/history — fetch build history
  if (path === '/api/apk/history' && request.method === 'GET') {
    return handleApkHistory(request, env);
  }

  return null; // Not handled — caller should fall through to other routes
}

async function handleApkBuild(request, env) {
  let body;
  try {
    body = await request.json();
  } catch (e) {
    return errorResponse('Invalid JSON body', 400);
  }

  const { appName, description, language, appType, apkType, features } = body;
  if (!appName || !description) {
    return errorResponse('appName and description are required', 400);
  }

  const pat = (env && env.GITHUB_PAT) || '';
  if (!pat) {
    return errorResponse('GitHub PAT not configured (env.GITHUB_PAT missing)', 500);
  }

  const buildId = Date.now().toString();
  const timestamp = new Date().toISOString();
  const featuresStr = Array.isArray(features) && features.length ? features.join(', ') : 'None';

  const buildRequestContent = `# APK Build Request

**Build ID:** ${buildId}
**Timestamp:** ${timestamp}

## App Details

| Field | Value |
|---|---|
| App Name | ${appName} |
| Description | ${description} |
| Language | ${language || 'kotlin'} |
| App Type | ${appType || 'utility'} |
| APK Type | ${apkType || 'online'} |
| Features | ${featuresStr} |

## Build Notes

This file was automatically generated by BrainForge APK Builder.
GitHub Actions will pick up this commit and build the APK automatically.

The APK artifact will be available for download from the GitHub Actions run page.
`;

  const repo = 'richardbrownmiami-commits/MyAI-Android-Build';
  const filePath = `BUILD_REQUEST.md`;

  // Get existing SHA if file exists
  let sha = undefined;
  try {
    const checkRes = await fetch(`https://api.github.com/repos/${repo}/contents/${filePath}`, {
      headers: {
        Authorization: `token ${pat}`,
        Accept: 'application/vnd.github.v3+json',
        'User-Agent': 'BrainForge-APK-Builder',
      },
    });
    if (checkRes.ok) {
      const existing = await checkRes.json();
      sha = existing.sha;
    }
  } catch (_) {}

  // Commit BUILD_REQUEST.md
  const commitBody = {
    message: `APK Build Request: ${appName} [${buildId}]`,
    content: btoa(unescape(encodeURIComponent(buildRequestContent))),
  };
  if (sha) commitBody.sha = sha;

  const commitRes = await fetch(`https://api.github.com/repos/${repo}/contents/${filePath}`, {
    method: 'PUT',
    headers: {
      Authorization: `token ${pat}`,
      Accept: 'application/vnd.github.v3+json',
      'Content-Type': 'application/json',
      'User-Agent': 'BrainForge-APK-Builder',
    },
    body: JSON.stringify(commitBody),
  });

  if (!commitRes.ok) {
    const err = await commitRes.text();
    return errorResponse(`GitHub commit failed: ${err}`, 502);
  }

  // Trigger workflow dispatch
  try {
    const dispatchRes = await fetch(
      `https://api.github.com/repos/${repo}/actions/workflows/build-apk.yml/dispatches`,
      {
        method: 'POST',
        headers: {
          Authorization: `token ${pat}`,
          Accept: 'application/vnd.github.v3+json',
          'Content-Type': 'application/json',
          'User-Agent': 'BrainForge-APK-Builder',
        },
        body: JSON.stringify({ ref: 'main', inputs: {} }),
      }
    );
    // 204 = success, 422 = workflow file missing (still OK, push trigger will fire)
    if (!dispatchRes.ok && dispatchRes.status !== 422) {
      console.warn('Workflow dispatch returned:', dispatchRes.status);
    }
  } catch (e) {
    console.warn('Workflow dispatch error (non-fatal):', e.message);
  }

  return jsonResponse({
    success: true,
    buildId,
    message: 'Build triggered — GitHub Actions is building your APK. Check /api/apk/history for status.',
  });
}

async function handleApkHistory(request, env) {
  const pat = (env && env.GITHUB_PAT) || '';
  if (!pat) {
    return jsonResponse([]);
  }

  const repo = 'richardbrownmiami-commits/MyAI-Android-Build';

  try {
    const runsRes = await fetch(
      `https://api.github.com/repos/${repo}/actions/runs?per_page=20`,
      {
        headers: {
          Authorization: `token ${pat}`,
          Accept: 'application/vnd.github.v3+json',
          'User-Agent': 'BrainForge-APK-Builder',
        },
      }
    );

    if (!runsRes.ok) {
      return jsonResponse([]);
    }

    const data = await runsRes.json();
    const runs = (data.workflow_runs || []).map((r) => {
      let status = 'Unknown';
      if (r.status === 'queued' || r.status === 'in_progress' || r.status === 'waiting') {
        status = 'Building';
      } else if (r.conclusion === 'success') {
        status = 'Ready';
      } else if (r.conclusion === 'failure' || r.conclusion === 'cancelled' || r.conclusion === 'timed_out') {
        status = 'Failed';
      } else if (r.status === 'completed' && !r.conclusion) {
        status = 'Ready';
      }

      return {
        id: r.id,
        name: r.display_title || r.name || ('Build #' + r.run_number),
        status,
        conclusion: r.conclusion,
        created_at: r.created_at,
        html_url: r.html_url,
        run_number: r.run_number,
      };
    });

    return jsonResponse(runs);
  } catch (e) {
    return jsonResponse([]);
  }
}
