name = "brainforge-api"
main = "index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "APPS_KV"
id = "c62f444539254734869f4fae5dc74755"

[[d1_databases]]
binding = "DB"
database_name = "brainforge-db"
database_id = 3814a86b-7054-465c-ae64-8bf99019cf6b"
