name = "bifrost"
main = "src/index.ts"
compatibility_date = "2026-05-27"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "BF", id = "b0b9c45d98d8407d93b1f3d9a7bf2665" }
]

[triggers]
crons = ["0 */6 * * *"]
