/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Project {
  'created' : Time,
  'name' : string,
  'aiModel' : string,
  'lastModified' : Time,
}
export interface Settings {
  'githubRepo' : string,
  'githubToken' : string,
  'masterAiModel' : string,
  'openRouterApiKey' : string,
  'defaultModel' : string,
  'termuxUrl' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'claimMasterModel' : ActorMethod<[string], undefined>,
  'createProject' : ActorMethod<[string], undefined>,
  'deleteProject' : ActorMethod<[string], undefined>,
  'getClaimedModels' : ActorMethod<[], Array<[string, string]>>,
  'getSettings' : ActorMethod<[], [] | [Settings]>,
  'listProjects' : ActorMethod<[], Array<Project>>,
  'saveSettings' : ActorMethod<[Settings], undefined>,
  'setProjectModel' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];