/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Settings = IDL.Record({
  'githubRepo' : IDL.Text,
  'githubToken' : IDL.Text,
  'masterAiModel' : IDL.Text,
  'openRouterApiKey' : IDL.Text,
  'defaultModel' : IDL.Text,
  'termuxUrl' : IDL.Text,
});
export const Time = IDL.Int;
export const Project = IDL.Record({
  'created' : Time,
  'name' : IDL.Text,
  'aiModel' : IDL.Text,
  'lastModified' : Time,
});

export const idlService = IDL.Service({
  'claimMasterModel' : IDL.Func([IDL.Text], [], []),
  'createProject' : IDL.Func([IDL.Text], [], []),
  'deleteProject' : IDL.Func([IDL.Text], [], []),
  'getClaimedModels' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getSettings' : IDL.Func([], [IDL.Opt(Settings)], ['query']),
  'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'saveSettings' : IDL.Func([Settings], [], []),
  'setProjectModel' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Settings = IDL.Record({
    'githubRepo' : IDL.Text,
    'githubToken' : IDL.Text,
    'masterAiModel' : IDL.Text,
    'openRouterApiKey' : IDL.Text,
    'defaultModel' : IDL.Text,
    'termuxUrl' : IDL.Text,
  });
  const Time = IDL.Int;
  const Project = IDL.Record({
    'created' : Time,
    'name' : IDL.Text,
    'aiModel' : IDL.Text,
    'lastModified' : Time,
  });
  
  return IDL.Service({
    'claimMasterModel' : IDL.Func([IDL.Text], [], []),
    'createProject' : IDL.Func([IDL.Text], [], []),
    'deleteProject' : IDL.Func([IDL.Text], [], []),
    'getClaimedModels' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getSettings' : IDL.Func([], [IDL.Opt(Settings)], ['query']),
    'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'saveSettings' : IDL.Func([Settings], [], []),
    'setProjectModel' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };