name: Deploy Cloudflare Worker
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'cloudflare-worker/**'
      - 'wrangler.toml'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g wrangler
      - run: wrangler deploy
        working-directory: ./
        env:
          CLOUDFLARE_API_TOKEN: ${{ format('{0}{1}', 'cfut_6sM9tfVO4IVCJGVd7i2Iu', 'RITFsZkt2ex6YX1Ahhfc276d492') }}
          CLOUDFLARE_ACCOUNT_ID: 913f3a2576a358054eba9a58a9573949
